# Generated by Django 4.1 on 2022-08-25 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_order_client'),
        ('core', '0003_bottlescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottlescount',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bottlescount',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='clients.order'),
        ),
    ]
