# Generated by Django 4.1 on 2022-08-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contacts',
        ),
    ]
