# Generated by Django 4.1 on 2022-08-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_order_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contacts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
